"""
06 -- EYES AND DAMAGE SHAPE KEYS. No external asset needed; runs standalone.

    blender --background --python blender/scripts/06_eyes.py

This is the script that fixes the measured defect at the root of the failed
runtime eye work, and it is the strongest argument for doing any of this in
Blender at all.

THE MEASUREMENT

    l_eye      weightTotal 0.00   dominantVerts 0
    r_eye      weightTotal 0.00   dominantVerts 0
    c_jaw      weightTotal 173.64 dominantVerts 178

(00_inspect.py re-derives this every run; it is in out/rig-facts.json.)

The eye bones exist and animate but deform NOTHING. This LOD has no eyeball
geometry -- the eye area is plain head skin. Two consequences the runtime could
not work around:

  - scaling those bones to swell an eye was a silent no-op
  - painting a sclera and iris onto the skin gave a decal with no socket behind
    it, which read as a staring mannequin

Both are asset problems, and an asset problem has to be fixed in the asset.

WHAT THIS ADDS

1. Real eyeballs, weighted 100% to l_eye / r_eye, so the bones finally drive
   something and the runtime inherits head motion for free.

2. Damage SHAPE KEYS on the body mesh, addressable by name:
       eye_close_L / eye_close_R     lid closing from swelling
       cheek_swell_L / cheek_swell_R
       brow_swell_L / brow_swell_R
   glTF carries these as morph targets, and three.js exposes them through
   `mesh.morphTargetDictionary`. That gives real blendshape-driven damage in
   place of bone scaling -- and unlike the 117 morphs FBX2glTF stripped the
   names from, these are named here and stay named.

   The displacement is generated by proximity falloff from the relevant bone,
   which is crude next to a sculpted blendshape but is anatomically in the
   right place and is fully reproducible. Treat it as a working default to
   sculpt over, not as a finished result.

SOCKET DEPTH. The sphere is inset slightly into the head rather than sat on the
surface. An eyeball flush with flat skin is exactly what made the runtime
version read as a golf ball glued to the face.
"""

import math
import os
import sys

import bpy
from mathutils import Vector

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import kitfit  # noqa: E402
from _common import (  # noqa: E402
    run,
    BONES, bone_world, log, open_work, save_work, select_only,
)

# Eyeball radius as a fraction of the interpupillary distance, measured off the
# rig rather than set absolutely, so it stays proportionate on any re-export.
RADIUS_OF_IPD = 0.26
# How far the ball sits back into the head, as a fraction of its own radius.
INSET_OF_RADIUS = 0.35

SCLERA = (0.86, 0.84, 0.80)
IRIS = (0.17, 0.11, 0.07)

# Shape-key reach and strength, both as fractions of the eye radius / body
# height. Reach controls how much of the face a swell recruits; too wide and
# the whole cheek inflates like a balloon.
CLOSE_REACH = 2.6
CLOSE_AMOUNT = 0.85
SWELL_REACH = 4.0
SWELL_AMOUNT = 0.45


def eye_positions(arm):
    left = bone_world(arm, BONES["eye_l"])
    right = bone_world(arm, BONES["eye_r"])
    return left, right, (left - right).length


def facing(left, right, head):
    """Which way the face points, derived rather than assumed.

    The eye-to-eye line gives the head's lateral axis; crossing it with world
    up gives forward. Which of the two results is the FRONT is settled by
    checking that the eyes sit forward of the head bone -- so this survives a
    re-export that flips the figure around.
    """
    across = (left - right).normalized()
    up = Vector((0.0, 0.0, 1.0))
    fwd = across.cross(up).normalized()
    mid = (left + right) / 2.0
    if fwd.dot(mid - head) < 0:
        fwd = -fwd
    return fwd


def build_ball(name, centre, radius, fwd, bone, arm):
    bpy.ops.mesh.primitive_uv_sphere_add(segments=24, ring_count=16,
                                         radius=radius, location=centre)
    ball = bpy.context.active_object
    ball.name = name
    ball.data.name = name + "_mesh"

    # Sit it back into the socket. Flush with the skin reads as a bead stuck on
    # the face; inset reads as an eye in a head.
    ball.location = ball.location - fwd * (radius * INSET_OF_RADIUS)
    bpy.context.view_layer.update()
    select_only(ball)
    bpy.ops.object.transform_apply(location=True)

    bpy.ops.object.shade_smooth()

    # 100% to the eye bone. This is what makes the bone deform something for
    # the first time.
    kitfit.pin_to_bone(ball, bone, arm)
    kitfit.set_material(ball, name + "_sclera", SCLERA, roughness=0.22)
    log("built %s: radius %.5f at %s" % (name, radius, bone))
    return ball


def add_shape_key(body, name, centre, reach, amount, direction):
    """Displace vertices near `centre`, with a smooth falloff, into a key.

    `direction` is either a Vector (push that way) or None (push along each
    vertex's own normal, which is what swelling does).
    """
    if body.data.shape_keys is None:
        body.shape_key_add(name="Basis", from_mix=False)
    key = body.shape_key_add(name=name, from_mix=False)
    key.value = 0.0
    key.slider_min = 0.0
    key.slider_max = 1.0

    mw = body.matrix_world
    inv = mw.inverted()
    moved = 0
    for i, v in enumerate(body.data.vertices):
        world = mw @ v.co
        d = (world - centre).length
        if d >= reach:
            continue
        # Smoothstep falloff. A linear one leaves a visible hard edge at the
        # boundary of the affected patch.
        t = 1.0 - (d / reach)
        w = t * t * (3.0 - 2.0 * t)
        push = direction if direction is not None else (mw.to_3x3() @ v.normal).normalized()
        key.data[i].co = inv @ (world + push * (amount * w))
        moved += 1
    log("shape key %s: %d verts within %.4f" % (name, moved, reach))
    return key


def main():
    open_work()
    arm, body = kitfit.context()

    kitfit.clear_previous(["eye_L", "eye_R"])
    left, right, ipd = eye_positions(arm)
    if ipd <= 1e-6:
        log("FAILED: eye bones coincide -- cannot derive a radius")
        return
    radius = ipd * RADIUS_OF_IPD
    head = bone_world(arm, BONES["head"])
    fwd = facing(left, right, head)
    log("ipd %.5f -> eyeball radius %.5f; facing %s"
        % (ipd, radius, tuple(round(c, 3) for c in fwd)))

    build_ball("eye_L", left, radius, fwd, BONES["eye_l"], arm)
    build_ball("eye_R", right, radius, fwd, BONES["eye_r"], arm)

    # Lid closure pushes the skin over the eye DOWN and slightly back, which is
    # how a swollen eye actually shuts -- the lid does not simply thin out.
    down = Vector((0.0, 0.0, -1.0))
    close_dir = (down * 0.8 - fwd * 0.2).normalized()
    add_shape_key(body, "eye_close_L", left, radius * CLOSE_REACH,
                  radius * CLOSE_AMOUNT, close_dir)
    add_shape_key(body, "eye_close_R", right, radius * CLOSE_REACH,
                  radius * CLOSE_AMOUNT, close_dir)

    # Swelling inflates along the surface normal, from a centre below and
    # outside each eye -- the cheekbone, which is where a hook lands.
    across = (left - right).normalized()
    for side, eye, sign in (("L", left, 1.0), ("R", right, -1.0)):
        cheek = eye + across * (sign * radius * 1.2) - Vector((0, 0, radius * 2.0))
        add_shape_key(body, "cheek_swell_" + side, cheek,
                      radius * SWELL_REACH, radius * SWELL_AMOUNT, None)
        brow = eye + Vector((0, 0, radius * 1.6))
        add_shape_key(body, "brow_swell_" + side, brow,
                      radius * (SWELL_REACH * 0.7), radius * SWELL_AMOUNT, None)

    names = [k.name for k in body.data.shape_keys.key_blocks]
    log("body now carries %d shape keys: %s" % (len(names), ", ".join(names)))
    log("NOTE: 07_export.py must run with export_morph=True or these are lost.")
    save_work()


run(main)
